# This GitHub Actions workflow prints messages and demonstrates accessing the event name.
# It runs on push events and displays the trigger information.
name: event-workflow
on:
    - push

jobs:
        print-event-name:
            runs-on: ubuntu latest
            steps:
                - name: print hi
                  run: echo hi
                - name: print event
                  run: echo "The event triggerd is ${{ github.event_name}}" 
                - name: print end
                  run: echo "end"   